# Generated by Django 4.0.5 on 2022-06-09 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('role', models.CharField(choices=[('1', 'MENTEE'), ('2', 'MENTOR'), ('3', 'ADVISOR')], default='1', help_text='Role of the user', max_length=20)),
                ('batch', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('None', 'None')], default='2019', max_length=10)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('college', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('degree', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('guidance', models.TextField(blank=True, default=None, null=True)),
                ('linkedin', models.URLField(blank=True, default=None, null=True)),
                ('github', models.URLField(blank=True, default=None, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teams')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
