# Generated by Django 4.0.5 on 2022-06-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_presentation'),
        ('users', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.teams'),
        ),
    ]
