# Generated by Django 4.0.5 on 2022-06-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_request_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('1', 'INCOMPLETE'), ('2', 'BOOKED')], default='1', help_text='Status of the request', max_length=20),
        ),
    ]
