# Generated by Django 4.0.5 on 2022-06-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
