# Generated by Django 4.0.5 on 2022-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='teams')),
                ('problem_statement', models.TextField()),
                ('presentation', models.FileField(upload_to='presentations/')),
                ('cookies', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
